#!/bin/bash

for i in {1..60..1}
do
	../blender_tanvi/blender -P src/warehouse_pillared_new.py -b
	mv "./datasets" "./datasets_${i}"
done
python3 src/dataset_merger.py
python3 src/GenerateLayouts.py
date